### ISSUE TITLE
[Bug]: Can't launch game after 1.1.1 update.

### ISSUE THREAD

**Issue by nicolasbaggio** [Lyall/GBFRelinkFix#39]
## Issue Summary:
Can't launch game after 1.1.1 update.

**Comment by 9niine** [comment]
same here

**Comment by ryuzzo** [comment]
Yeah same here, hopefully a fix will happen soon

**Comment by Lyall** [comment]
Working on it right now.

**Comment by Lyall** [comment]
Okay, [v1.0.9 is out](https://github.com/Lyall/GBFRelinkFix/releases) with support for the latest game update. 

I'm going to keep this issue open and pinned for a bit. If anyone runs in to any issues with this update, please post them here and I will have a look. I obviously haven't had much time to test things out but I have gone through all the code and it should be fully-functional.

**Comment by xEstarossa** [comment]
Hi, thanks for the update
I notice when I fought Lucilius, some HUD effects (like screen red when you're low life - AOE Attack, etc..) is still in 16/9
I didn't notice these of the precedent vers. of the fix
Maybe it's the game or the boss, don't know
I want to point it out

**Comment by Glfz65** [comment]
same here. and it's exists in v1.0.8
here is the screenshot and logs.
Thank you for making this patch♥

logs
[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14604203/GBFRelinkFix.log)

screenshot
![granblue_fantasy_relink_2024_03_14_19_27_14_511](https://github.com/Lyall/GBFRelinkFix/assets/163434292/3092b290-a53b-4513-a137-5e1d82e62c82)
![granblue_fantasy_relink_2024_03_14_19_26_44_330](https://github.com/Lyall/GBFRelinkFix/assets/163434292/05667887-a665-46b0-97d8-59f4b9254e29)

![granblue_fantasy_relink_2024_03_14_20_19_41_215](https://github.com/Lyall/GBFRelinkFix/assets/163434292/83a0e509-65bf-4b46-bd26-c3d2d9064230)
![granblue_fantasy_relink_2024_03_14_19_47_54_837](https://github.com/Lyall/GBFRelinkFix/assets/163434292/7697c32b-7a51-4497-bd03-2a287ef8b6aa)

**Comment by Lyall** [comment]
Yeah there's still quite a few UI elements that should be spanned to fill the screen. The problem with the way I'm doing it now is that I only span certain UI elements from a list of IDs. So if I want to add something, I need to encounter it in-game then find the ID for it and add it. 

It's not the best approach and I would love to have a better way of doing it but just spanning stuff globally breaks so much stuff. I should probably dump the game files with [GBFRDataTools](https://github.com/Nenkai/GBFRDataTools) and see if there's a way to view the actual assets outside of the game.

**Comment by RageList** [comment]
Not sure if 1.0.9 is also for 1.1.1 or just 1.1.0
But the game won't launch for 1.1.1
And the log seemed normal I guess?
[GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14608030/GBFRelinkFix.log)

**Comment by Lyall** [comment]
> Not sure if 1.0.9 is also for 1.1.1 or just 1.1.0 But the game won't launch for 1.1.1 And the log seemed normal I guess? [GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14608030/GBFRelinkFix.log)

It should work fine on v1.1.1. Is that resolution in your log a typo? Are you really playing at 777x437? That may be causing issues.

**Comment by nicolasbaggio** [comment]
Yeah the issue is fixed, thank you so much!

**Comment by nrsolo** [comment]
Hmm, I still can't launch the game, mod 1.0.9 on v1.1.1. Default config using desktop resolution of 3440*1440. Interestingly I never have a dinput8.dll in my game folder in the first place.

**Comment by vsmmvs** [comment]
it doesn't seem to work in 1.1.2

**Comment by RageList** [comment]
> it doesn't seem to work in 1.1.2

You could try using d3d11.dll asi loader then replace winmm.dll with the original one. That fixed the game not launching in 1.1.1 and 1.1.2 for me.  
You can find the link in this repo's readme. Saying this just in case anyone has the same problem.
Apparently for me the problem caused because I used steamless (Idk if it's allowed to mention it here), even though it worked without any issue in 1.0.5.

**Comment by zerovirus999** [comment]
I just got the game and can't get it to work with 1.1.2 either. Not sure if I'm not following the instructions correctly, but I placed all the filles in the installation directory and tried to load the game. I still see black borders.

**Comment by Riri013** [comment]
Installed the update few days ago and it worked. Launched the game today and its not launching again.

**Comment by HellsMike** [comment]
> Installed the update few days ago and it worked. Launched the game today and its not launching again.

Try to delete old GBFRelinkFix files, launch game without fix, then close the game and extract GBFRelinkFix 1.0.9 in the main game folder as usual.

It worked for me, i don't know if lauching vanilla game is required, but this is what i've done.

**Comment by zerovirus999** [comment]
> > it doesn't seem to work in 1.1.2
> 
> > Installed the update few days ago and it worked. Launched the game today and its not launching again.
> 
> Try to delete old GBFRelinkFix files, launch game without fix, then close the game and extract GBFRelinkFix 1.0.9 in the main game folder as usual.
> 
> It worked for me, i don't know if lauching vanilla game is required, but this is what i've done.
> 
> [GBFRelinkFix.log](https://github.com/Lyall/GBFRelinkFix/files/14650950/GBFRelinkFix.log)

I think I'm missing something in the instructions. I paste the files in the install directory. Then what do I do? So I simply launch the game from Steam or am I supposed to run something else?

**Comment by HellsMike** [comment]
> I think I'm missing something in the instructions. I paste the files in the install directory. Then what do I do? So I simply launch the game from Steam or am I supposed to run something else?

Launch the game from Steam

**Comment by zerovirus999** [comment]
> > I think I'm missing something in the instructions. I paste the files in the install directory. Then what do I do? So I simply launch the game from Steam or am I supposed to run something else?
> 
> Launch the game from Steam

It appears you need to put the GBFRelinkFix.ini and GBFRelinkFix.asi files in a folder name scripts. If you download the files from the master/main branch, that is not the case which is why it wasn't working. @Lyall, I would suggest either adding this part in the read me or fixing the file structure in the repo.
